
 /******* DIM gEOGRAFIA ******/ 
exec ETL_STG_CIUDADES ;
exec ETL_STG_DEPARTAMENTOS ;
exec ETL_STG_DIM_GEOGRAFIA ;
exec ETL_DIM_GEOGRAFIA ;

SELECT * FROM STAR.DIM_GEOGRAFIA;


/************ DIM PRODUCTO *******/

exec ETL_STG_PRODUCTOS ;
exec ETL_STG_PRESENTACIONES ;
exec ETL_STG_DIM_PRODUCTOS ;
exec ETL_DIM_PRODUCTOS;

SELECT * FROM STAR.DIM_PRODUCTOS;


/************ DIM  CLIENTES *******/

exec ETL_STG_RUBROS ;
exec ETL_STG_SUBRUBROS ;
exec ETL_STG_CLIENTES_RUBROS ;
exec ETL_STG_DIM_CLIENTES ;

exec ETL_DIM_CLIENTES;

SELECT * FROM STAR.DIM_CLIENTES;


/************ DIM TIEMPO *******/

exec ETL_STG_DIM_TIEMPO ;
exec ETL_DIM_TIEMPO ;

SELECT * FROM STAR.DIM_TIEMPO;


/************ CARGADO DE LA FACT TABLE *****/

SELECT MAX(FECHA), MIN(FECHA) FROM distribuidor.venta;
--31/07/1999    31/01/1998



/************ FACT VENTA *******/
exec ETL_STG_FACT_VENTA('01/01/1998', '31/07/1999') ;


-- REVISAR DATOS ***/ 
SELECT * FROM STG_FACT_VENTA;


exec ETL_FACT_VENTAS( '01/01/1998', '31/07/1999' ) ;

SELECT * FROM STAR.FACT_VENTA;

SELECT * FROM STAR.DIM_TIEMPO;


/******** REVISAR LA LOG DE PROCESOS ****/ 
 
SELECT * FROM LOG_DE_PROCESOS
ORDER BY FEC_FIN DESC








